# Generated by Django 3.1.2 on 2020-10-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IterationCode', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('PlannedEndDate', models.DateTimeField()),
                ('RealEndDate', models.DateTimeField()),
                ('PlannedEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Progress', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='IterationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IterationTaskCode', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('PlannedEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('PlannedHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Creation', models.CharField(max_length=50)),
                ('Edition', models.CharField(max_length=50)),
                ('IterationCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iteration')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEntry',
            fields=[
                ('PlanningEntryId', models.AutoField(primary_key=True, serialize=False)),
                ('Creation', models.CharField(max_length=50)),
                ('Edition', models.CharField(max_length=50)),
                ('PlannedHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('PlannedEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Anotation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('Document', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=100)),
                ('Mail', models.CharField(max_length=100)),
                ('ProxyFactor', models.DecimalField(decimal_places=1, max_digits=3)),
                ('AvailableWeekHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanningPeriod',
            fields=[
                ('PeriodId', models.AutoField(primary_key=True, serialize=False)),
                ('PeriodTitle', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('AvailableHours', models.IntegerField()),
                ('PlannedEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('PlannedHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealHours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Anotation', models.CharField(max_length=250)),
                ('PlanningEntryId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.planningentry')),
            ],
        ),
        migrations.AddField(
            model_name='planningentry',
            name='Document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.teammember'),
        ),
        migrations.AddField(
            model_name='planningentry',
            name='IterationCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iteration'),
        ),
        migrations.AddField(
            model_name='planningentry',
            name='IterationTaskCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iterationtask'),
        ),
        migrations.AddField(
            model_name='planningentry',
            name='ProjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project'),
        ),
        migrations.AddField(
            model_name='iterationtask',
            name='ProjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='ProjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project'),
        ),
        migrations.CreateModel(
            name='TaskProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('EffortAvg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('IterationCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iteration')),
                ('IterationTaskCode', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iterationtask')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project')),
            ],
            options={
                'unique_together': {('IterationTaskCode', 'IterationCode', 'ProjectId')},
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequirementId', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('EspecificationLink', models.CharField(max_length=100)),
                ('Creation', models.CharField(max_length=50)),
                ('Edition', models.CharField(max_length=50)),
                ('PlannedEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('RealEffort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project')),
            ],
            options={
                'unique_together': {('RequirementId', 'ProjectId')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='planningentry',
            unique_together={('IterationTaskCode', 'PlanningEntryId', 'IterationCode', 'ProjectId')},
        ),
        migrations.CreateModel(
            name='IterationTaskHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Annotation', models.CharField(max_length=250)),
                ('IterationCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iteration')),
                ('IterationTaskCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.iterationtask')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project')),
            ],
            options={
                'unique_together': {('IterationTaskCode', 'Date', 'IterationCode', 'ProjectId')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='iterationtask',
            unique_together={('IterationTaskCode', 'IterationCode', 'ProjectId')},
        ),
        migrations.AlterUniqueTogether(
            name='iteration',
            unique_together={('IterationCode', 'ProjectId')},
        ),
    ]
